# Site settings
name: Marek Kohn
description: "Hi! This site is still under construction! ğŸ—ï¸ ğŸš§"
url: "https://makohn.de"

github_username: makohn
twitter_username: makohn_
email: info@makohn.de

avatar_img_path: "https://pics.paypal.com/00/s/OTYwWDk2MFhKUEc/p/ZjhmZWJkNGItMjczYy00YTU1LWFjODYtOGUyMWQ1NDQ5NDFi/image_58.jpg"

# Build settings
markdown: kramdown
permalink: pretty

# Make .well-known folder accessible
include: [".well-known"]